package:
  name: pairing
  version: "0.0.0"

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - mdtraj

test:
  requires:
    - pytest
  imports:
    - pairing

about:
  home: https://github.com/mattwthompson/pairing
  license: MIT License
  summary: analyze pairing and clustering of molecular systems
